---
title: "Welcome"
format: html
editor: visual
---

Welcome to the `INAB In-House Analyses` guide.

## Introduction

This page provides internal documentation for performing standard bioinformatics analyses at the lab, including setup, data preprocessing, and downstream workflows.

> **Note:** This document is for internal use only.

## Getting Started

The goal of this guide is to bridge the gap between wet-lab experiments and dry-lab results.

You will learn:

-   how to prepare your data correctly
-   how to use basic Unix commands
-   how to run analysis

## Your Roadmap

1.  [**Data & Metadata**](qmd/data_cleaning.qmd)**:** Learn the "Golden Rules" of file naming and organization.
2.  [**Unix Commands**](qmd/unix.qmd)**:** Basic commands to navigate folders, inspect files, and prepare data for analysis.
3.  [**Analysis Pipelines**](qmd/analysis.qmd)**:** Standardized workflows for INAB projects.

## Contributing

Your input is invaluable - whether it's suggesting a new chart/analysis or reporting a bug, we welcome and greatly appreciate your feedback! 

Feel free to open a [GitHub issue](https://github.com/natanast/immunovisual/issues) or contact us via `inab.bioinformatics@lists.certh.gr`.


## Author

```{r}

```

`r fontawesome::fa("github", "black")` [Natasa Anastasiadou](https://github.com/natanast)
